web/django_k8s/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('home/', include('feedbacks.urls')),
]


from django.views.generic import RedirectView

# To check following code not wkg and by default catalog page comes.
urlpatterns += [
    path('', RedirectView.as_view(url='/home', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/feedbacks/urls.py
from django.urls import path
from feedbacks import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='feedbacks/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),

    # Home
    path('', views.index, name='index'),

    path('register', views.register, name='register'),
    path('user_details', views.UserListView.as_view(), name='user_details'),
    path('searchuser/', views.SearchUserView.as_view(), name='searchuser'),

    # plot UPC generated
    path('selcircle/', views.SearchByCirclePlot, name='selcircle'),
    path('plot/', views.plot, name='plot'),
 
    # plot feedback done
    path('feedback/', views.SearchByCircleFeedPlot, name='feedback'),
    path('feed_plot/', views.feedplot, name='feedplot'),

    # circle-wise search
    path('searchbycircle/', views.SearchByCircle, name='searchbycircle'),
    path('search_results3/', views.SearchResultsView3.as_view(), name='search_results3'),
    path('csv_circle_wise/', views.export_csv_circle_wise, name='csv_circle_wise'),
    
    # search by ssa
    path('searchbyssa', views.SearchBySsa, name='searchbyssa'),
    path('ajax/load-ssas/', views.load_ssas, name='ajax_load_ssas'),
    path('search_results4/', views.SearchResultsView4.as_view(), name='search_results4'),
    path('csv_ssa_wise/', views.export_csv_ssa_wise, name='csv_ssa_wise'),

    # search by msisdn sequence
    path('searchsingle/', views.HomePageView2.as_view(), name='searchsingle'),    
    path('search_results2/', views.SearchResultsView2.as_view(), name='search_results2'),
    # path('csv/', views.export_csv_single, name='csv'),
    

    path('mobiles/', views.MobileListView.as_view(), name='mobiles'),

    path('mobile/<int:pk>', views.MobileDetailView, name='mobile_detail'),
    # path('feedback_form/<int:pk>', views.FeedbackUpdateView, name='feedback'),
    # path('exportfulldata/', views.export_full_data, name='export_full_data'),

    
       
    # path('searchfilter/', views.search_filter, name='searchfilter'),
 
    
    # path('filter1/', views.all_mobiles, name='filter1'),
    # path('show/', views.Show_data, name='show'),
    
    # path('xls/', views.export_users_xls, name='xls'),
    
    # search by upc_date range
    # path('searchbyupc/', views.HomePageView.as_view(), name='searchbyupc'),
    # path('search_results/', views.SearchResultsView.as_view(), name='search_results'),
    # path('export_csv_upc_range/', views.export_csv_upc_range, name='export_csv_upc_range'),

]

web/feedbacks/models.py
from django.db import models

from django.conf import settings

from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.utils import timezone

User = settings.AUTH_USER_MODEL


class Circle(models.Model):
    name = models.CharField(max_length=50, default=0)

    def __str__(self):
        # return u'{0}'.format(self.circle_name)
        return str(self.name)

class Ssa(models.Model):
    name = models.CharField(max_length=50, default=0)
    circle = models.ForeignKey(Circle, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return str(self.name)
        # return u'{0}'.format(self.circle_name)
        # return f"{self.circle}-{self.name}"        


class Mobile(models.Model):
   
    choice = (
        ('poor_network_coverage', 'Poor network coverage'),    
        ('low_data_speed', 'Low data speed'),
        ('absence_of_4g', 'Absence of 4G'),
        ('poor_customer_care', 'Poor customer care'),
        ('recharge_issues', 'Recharge issues'),
        ('billing_issues', 'Billing issues'),
        ('high_tariff', 'High Tariff'),
        ('vas', 'Value Added Services'),
        ('others', 'Others'),
        ('not_answered', 'Not Answered'),
        ('select', 'Select reason'),
    )

    # bool1 = models.BooleanField(blank=True, null=True)
    # bool2 = models.BooleanField(blank=True, null=True)
    # str1 = models.CharField(max_length=10, null=True, blank=True)
    # str2 = models.CharField(max_length=10, null=True, blank=True)
    msisdn = models.CharField(max_length=13)    
    account_no = models.CharField(max_length=10, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=300, blank=True, null=True)
    # city = models.CharField(max_length=30, null=True, blank=True)
    ssa = models.ForeignKey(Ssa, on_delete=models.SET_NULL, blank=True, null=True)
    circle = models.ForeignKey(Circle, on_delete=models.SET_NULL, blank=True, null=True)
    upc_date = models.DateField(blank=True, null=True)
    upc_expiry_date = models.DateField(blank=True, null=True)
    connection_type = models.CharField(max_length=15, blank=True, null=True)
    avg_revenue = models.CharField(max_length=100, blank=True, null=True) 
    
    portout_apply_date = models.DateField(null=True, blank=True)
    portout_date = models.DateField(null=True, blank=True)
    port_status = models.CharField(max_length=50, null=True, blank=True)

    called_counter = models.IntegerField(default = 0) 

    reason_for_PO = models.CharField(
        max_length=30,
        choices=choice,
        blank=False,
        default='select',
        help_text='Reason for opting PO',
    )

    remarks = models.TextField(null=True, blank=True)
    feedback_date = models.DateTimeField(null=True, blank=True)
    user = models.CharField(max_length=50,null=True, blank=True)


    class Meta:
        ordering = ['-avg_revenue', 'circle', 'ssa', 'upc_date', 'msisdn']
         
    
    def __str__(self):
        """String for representing the Model object."""
        return str(self.pk)
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('mobile_detail', args=[str(self.id)])

web/feedbacks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.core.paginator import Paginator
# from django.conf import settings
from django.utils import timezone
from django.db.models import Q 
from datetime import datetime, timedelta
import csv
import json
from django.contrib import messages

from .forms import SsaForm, FeedbackModelForm, UserRegisterForm
from .models import Mobile, Circle, Ssa

import pandas as pd
import numpy as np
from .utils import get_plot, get_plot_upc
from django_pandas.io import read_frame

from django.contrib.auth.models import User


# Circle user creation
@login_required
@permission_required('is_superuser')
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('user_details')
    else:
        form = UserRegisterForm()
        return render(request, 'feedbacks/register.html', {'form': form})


# registered user details
class UserListView(LoginRequiredMixin, generic.ListView):
    model = User
    # template_name = 'feedbacks/user_list.html'
    # paginate_by = 20


class SearchUserView(generic.ListView):
    model = User
    #template_name = 'feedbacks/mobile_list.html'

    def get_queryset(self):
        
        query = self.request.GET.get('usr')
        if len(query) == 0:          
            messages.warning(self.request, 'Please enter search string')
            return reverse('searchuser')
        else:
            object_list = User.objects.filter(
                Q(username__icontains = query) | Q(first_name__icontains = query) | Q(last_name__icontains = query) | Q(email__icontains = query)  
            )
        
            return object_list



# UPC REPORT

def SearchByCirclePlot(request):
    context = {}
    context['form'] = SearchForm({'report_type' : 'Chart'})
    if request.GET: 
        temp = request.GET['circle_id'] 
        # print(temp) 
    return render(request, 'feedbacks/sel_circle_plot.html', context)

def plot(request):

    cir_id = request.GET['circle_id'] 
    upc_start_dt = request.GET.get('d1')
    upc_end_dt = request.GET.get('d2')
    # converting string to datetime and adding 1 day
    upc_end_dt1 = datetime.strptime(upc_end_dt, "%Y-%m-%d") + timedelta(days=1)
    report_type = request.GET.get('report_type')
    
    Q3 = Q(upc_date__gte=upc_start_dt)
    Q2 = Q(upc_date__lte=upc_end_dt1)

    if int(cir_id) == 0:
        Q1 = Q(circle_id__in = [1,2,3,4,5,6,7,8,9])
    else:
        Q1 = Q(circle_id=cir_id)
    
    start_dt = datetime.strptime(upc_start_dt, "%Y-%m-%d")
    # print(start_dt.strftime("%d-%b-%Y"))
    start_dt = start_dt.strftime("%d-%b-%Y")
    end_dt = datetime.strptime(upc_end_dt, "%Y-%m-%d")
    end_dt = end_dt.strftime("%d-%b-%Y")
    
    if (int(cir_id) > 0):

        mob = Mobile.objects.filter(Q1 & Q2 & Q3)
        data = read_frame(mob)
        # print(data['ssa'])
        data2 = data.value_counts(['ssa']).reset_index(name='Total UPC generated')
        # print(data2)
        data2.rename(columns = {'ssa': 'SSA'}, inplace = True)
        qs = Circle.objects.filter(id=cir_id)
        for cir in qs:
            name1 = cir.name
        xlabel = "SSA Name"

    else:
        
        mob = Mobile.objects.filter(Q1 & Q2 & Q3) 
        data = read_frame(mob)
        # print(data.msisdn)
        data2 = data.value_counts(['circle']).reset_index(name='Total UPC generated')
        # print(data2)
        data2.rename(columns = {'circle': 'CIRCLE'}, inplace = True)
        name1 = "EZ circles"
        xlabel = "Circle Name"
    
    title = "Total UPC generated"
    ylabel = "UPC count"
    circle = []
    count = []

    for z in range(len(data2)):
        circle.append((data2.iloc[z,0]))
        count.append((data2.iloc[z,1]))
    
    if report_type == "Report":
        
        circnt = {}
        # circnt = {circle[i]: count[i] for i in range(len(circle))} 

        circnt = dict(zip(circle, count))
        # print(circnt)

        context = {
            # 'circle' : circle,
            'title' : title,
            'upc_start_dt' : start_dt,
            'upc_end_dt' : end_dt,
            'data' : circnt,
        }
        return render(request, 'feedbacks/report_upc.html', context)

    else:
        # print(data2)
        
        chart = get_plot_upc(data2, name1, start_dt, end_dt, title, xlabel, ylabel)
        
        sum = 0
        for i in range(len(count)):
            sum += count[i]
        if sum > 0:
            # x = [x.ssa for x in qs]
            context = {
                # 'df' : data1.to_html(),
                'chart' : chart,
                'upc_start_dt' : start_dt,
                'upc_end_dt' : end_dt,
            }
        else:
            context = {
                'chart' : None,
                'upc_start_dt' : start_dt,
                'upc_end_dt' : end_dt,
            }
        return render(request, 'feedbacks/chart.html', context)


# Feedback report

def SearchByCircleFeedPlot(request):
    context = {}
    context['form'] = SearchForm({
        'feed_status' : 'Completed', 
        'report_type' : 'Chart',
        'po_reason' : 'No'
        })
    return render(request, 'feedbacks/plot_feed.html', context)


def feedplot(request):
    cir_id = request.GET['circle_id'] 
    upc_start_dt = request.GET.get('d1')
    upc_end_dt = request.GET.get('d2')
    feed_status = request.GET.get('feed_status')
    report_type = request.GET.get('report_type')
    po_reason = request.GET.get('po_reason')

    start_dt = datetime.strptime(upc_start_dt, "%Y-%m-%d")    # string to date conversion
    # print(start_dt.strftime("%d-%b-%Y"))
    start_dt = start_dt.strftime("%d-%b-%Y")    # format change
    end_dt = datetime.strptime(upc_end_dt, "%Y-%m-%d")
    end_dt = end_dt.strftime("%d-%b-%Y")

    reasons = ['Billing issues', 'Value Added Services', 'Poor network coverage', 'High tariff', 'Low data speed', \
            'Absence of 4G', 'Poor customer care', 'Recharge issues', 'Others']

    
        
    if feed_status == 'Pending':                
        Q4 = (Q(feedback_date__isnull = True) |  Q(reason_for_PO__exact = '') |  Q(reason_for_PO__startswith = 'Not Answered'))
    
    else:        
        Q4 = (Q(feedback_date__isnull = False) & Q(reason_for_PO__in = reasons))

    upc_end_dt1 = datetime.strptime(upc_end_dt, "%Y-%m-%d") + timedelta(days=1)
    Q3 = Q(upc_date__gte=upc_start_dt)
    Q2 = Q(upc_date__lte=upc_end_dt1) 

    if int(cir_id) == 0:
        Q1 = Q(circle_id__in = [1,2,3,4,5,6,7,8,9])
    else:
        Q1 = Q(circle_id=cir_id)

    # print("Entered data: ", cir_id, po_reason, feed_status)

    if feed_status == 'Completed':
        title = "Customer Feedback completed"
        ylabel = "Feedback taken"
        xlabel = "SSA Name"
        
    else:
        title = "Customer Feedback pending"
        ylabel = "Feedback pending"
        xlabel = "SSA Name"
        
    
    if int(cir_id) == 0:
        xlabel= "Circle Name"
        name1 = "EZ circles"
    else:
        xlabel= "SSA name"
        qs = Circle.objects.filter(id=cir_id)
        for cir in qs:
            name1 = cir.name
    total = 0

    if int(cir_id) > 0 and feed_status == 'Completed' and po_reason=="Yes":        
           
        mob = Mobile.objects.filter(Q1 & Q2 & Q3 & Q4)
        data = read_frame(mob)
        # print(data)
        data2 = data.value_counts(['ssa','reason_for_PO']).reset_index(name='feedback')
        data2.rename(columns = {'ssa': 'SSA'}, inplace = True)
        total = data2.shape[0]
        
    elif (int(cir_id) > 0 and feed_status == 'Completed' and po_reason=="No") or \
        (int(cir_id) > 0 and feed_status == 'Pending'):

        mob = Mobile.objects.filter(Q1 & Q2 & Q3 & Q4)
        data = read_frame(mob)
        data2 = data.value_counts(['ssa']).reset_index(name='feedback')
        data2.rename(columns = {'ssa': 'SSA'}, inplace = True)
        data_dict = json.loads(data['ssa'].value_counts().to_json())
        total = len(data_dict)
        # print("Rows: ", total)
    
    elif (int(cir_id) == 0) and po_reason=="Yes" and feed_status == 'Completed':
        mob = Mobile.objects.filter(Q1 & Q2 & Q3 & Q4) 
        data = read_frame(mob)
        data2 = data.value_counts(['circle','reason_for_PO']).reset_index(name='feedback')
        data2.rename(columns = {'circle': 'CIRCLE'}, inplace = True)
        total = data2.shape[0]
        
    elif (int(cir_id) == 0) and (feed_status == 'Completed' and po_reason=="No") or (feed_status == 'Pending'):
        
        mob = Mobile.objects.filter(Q1 & Q2 & Q3 & Q4) 
        data = read_frame(mob)
        data2 = data.value_counts(['circle']).reset_index(name='Count')
        data2.rename(columns = {'circle': 'CIRCLE'}, inplace = True)
        data_dict = json.loads(data['circle'].value_counts().to_json())
        total = len(data_dict)
        # print("PENDING")
    
    else:
        # print("Check combination")
        pass

    # circle = []
    # reason = []
    # count = []
    
    # p = ''    
    # count_po = [0,0,0,0]    
    # q = 0

    # if  po_reason=="Yes" and feed_status=='Completed':

    #     for z in range(len(data2)):
    #         circle.append((data2.iloc[z,0]))

    #         p = data2.iloc[z,1]
    #         q = int(data2.iloc[z,2])
            
    #         if p == 'Others':
    #             count_po[0] += q
    #         elif p == 'Bad network':
    #             count_po[1] += q
    #         elif p == 'High tariff':
    #             count_po[2] += q

web/feedbacks/templates/feedbacks/branch_dropdown_list_options.html
<option value="">---------</option>
{% for ssa in ssas %}
<option value="{{ ssa.pk }}">{{ ssa.name }}</option>
{% endfor %}

web/feedbacks/templates/feedbacks/event_detail.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>{{ object.name }}</h2>
  <p class="text-muted">{{ object.date }}</p>
{% endblock %}

web/feedbacks/templates/feedbacks/feed_report_no.html
{% extends 'base_generic.html' %}
{% block title %}Details by SSA{% endblock %}


{% block content %}
<h3>{{ title }} between {{ upc_start_dt }} and {{ upc_end_dt }}</h3>

<table class="w3-table w3-table-all">
    <thead>
      <tr>        
        <th scope="col">CIRCLE/SSA</th>
        <th scope="col">COUNT</th>
      </tr>
    </thead>
  {% for key, value in data_dict.items %}
      <tr>
          <td>{{ key }}</td>
          <td>{{ value }}</td>
          
      </tr>
  {% endfor %}
  </table>

{% endblock %}

web/feedbacks/templates/feedbacks/feed_report_yes.html
{% extends "base_generic.html" %}
{% block title %}
  Feedback report
{% endblock %}

{% block content %}
<h3>{{ title }} between {{ start_dt }} and {{ end_dt }}:</h3>
<table class="w3-table w3-table-all">
    <th class="w3-table>
{{ data2 | safe }}</th>
</table>
{% endblock %}

web/feedbacks/templates/feedbacks/feedback_taken_already.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MNP Feedback portal</title>
</head>
<body>
   

{% include 'feedbacks/includes/messages.html' %}


{% if mobile %}
<font color='red'>
<center>
<H1> Feedback already taken for {{ mobile.msisdn }} on {{ mobile.feedback_date }}</H1> 
<H3>You may close this window.</H3>

</center>
</font>
{% endif %}
 
</body>
</html>

web/feedbacks/templates/feedbacks/forms1.html
{% extends "base_generic.html" %}
{% load static %}
 
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


{% block content %}
<font color = "blue">
  <center> <h1 class="bg-primary text-white">Customer feedback update form</h1></center>
  <br>
  <div class="form-group">
  <form method="POST">
    
      {% csrf_token %}
      {{ form.as_p }}

      <button class="btn btn-secondary">Submit</button>
  </form>
</div>
  {% endblock %}

web/feedbacks/templates/feedbacks/main.html
{% extends 'base.html' %}

{% block content %}
<div id="alert-box"></div>

<form class="mt-5" id="circle-form">
    {% csrf_token %}
    <div class="ui selection dropdown" id="circles">
        <input type="hidden" name="circle">
        <i class="dropdown icon"></i>
        <div class="default text" id="circle-text">Circle</div>
        <div class="menu" id="circles-data-box">
            <!-- <div class="item" data-value="{{circle}}">{{circle.circle_name}}</div>                       -->
        </div>
    </div>
    <div class="ui selection dropdown" id="ssas">
        <input type="hidden" name="ssa">
        <i class="dropdown icon"></i>
        <div class="default text" id="ssa-text">SSA</div>
        <div class="menu" id="ssas-data-box">
            <!-- <div class="item" data-value="{{circle}}">{{circle.circle_name}}</div>                       -->
        </div>
    </div>

    <div id="btn-box" class="mt-5 not-visible">
        <button type="submit" class="ui primary button">Save</button>
    </div>
</form>
{% endblock content %}

web/feedbacks/templates/feedbacks/manual.html
{% extends 'base_generic.html' %}
{% block title %}Details by SSA{% endblock %}


{% block content %}
<table>
  {% for key, value in data_dict.items %}
      <tr>
          <td>{{ key }}</td>
          <td>{{ value }}</td>
          
      </tr>
  {% endfor %}
  </table>

{% endblock %}

web/feedbacks/templates/feedbacks/pd.html
{% extends "base_generic.html" %}
{% block title %}<title>MNP feedback portal - Pandas</title>{% endblock %}
{% block content %}
<table><tr><td>
<font color="blue">
    <div id="my_table"> {{ df | safe }} </div> 
</font>
</td>
</tr>
<tr>
<td>
<font color="teal">
    <div id="my_table"> {{ df2 | safe }} </div> 
</font>
</td>
</tr>
</table>



{% endblock %}

web/feedbacks/templates/feedbacks/report_upc.html
{% extends "base_generic.html" %}
{% block title %}
  Feedback report
{% endblock %}

{% block content %}
<p><h3><center>{{ title }} between {{ upc_start_dt }} and {{ upc_end_dt }}</center></h3></p>
    <br>

{% if data.items %}
<table class="blueTable" style="width:400px">
    <thead>
      <tr>        
        <th scope="col">CIRCLE/ SSA</th>
        <th scope="col">COUNT</th>
        </tr>
    </thead>
    <tbody>

{% for key, value in data.items %}
    <tr class="blueTableRow">
            <td width=10%> {{ key }}: </td> 
            <td width=10%> {{ value }} </td>
        </tr>
        
    {% endfor %}
    </tbody>
    </table>

    {% else %}
    <p> <h4 style="color: green"> <center>
      *****************************************************<BR>
      No data found for the selected range of dates.<BR>
      *****************************************************
  
 </center></h4></p>
    {% endif %}
 

{% endblock %}

web/feedbacks/templates/feedbacks/sel_msisdn_upc_copy.html
{% extends "base_generic.html" %}
{% block title %}<title>MNP feedback portal - Search by MSISDN/ UPC_DATE</title>{% endblock %}
{% block content %}

<p> <h2 style="color: green">Search:</h2></p>
  <form action="{% url 'search_results2' %}" method="get" >
    <table style="width:50%">
      <tr>
        <td style="color:#0000ff">MSISDN/ UPC_DATE:&nbsp;&nbsp;&nbsp;&nbsp;
          <input type="text"  class="text" name="q" placeholder="Date format: 2020-10-16"> 
        </td>
        <td>
          <input type="submit" class="btn btn-primary" value="Search">
        </td>
        <td>
          <button type="reset" class="btn btn-warning" id="id_clear_filters" onclick="return resetForm(this.form);">
            Clear Filters
          </button>
        </td>
        <td>
          <input type="submit" class="btn btn-info" formaction="{% url 'csv' %}" value="Export CSV"/>
        </td>
      </tr>
    </table>    
    
  </form>

  {% endblock %}

web/feedbacks/templates/feedbacks/sel_ssa.html
{% extends 'base_generic.html' %}
{% block title %}Search by SSA{% endblock %}


{% block content %}

<p> <h3 style="color: rgb(6, 53, 13)">Details of Portout UPC by SSA (Feedback can be updated after search):</h3></p>

  <form method="get" action='.' id="ssaForm" data-ssas-url="{% url 'ajax_load_ssas' %}" validate>
   <b>
    <table style="width:25%">
      <tr><td style="color:#0000ff">Circle:&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
        {{ form.circle }}
      </td></tr>
      <tr><td><br>  </td></tr>
      <tr><td style="color:#0000ff" >SSA:&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
        {{ form.ssa }}
      </td></tr>
      <tr><td><br>  </td></tr>
      <tr><td style="color:#0000ff">UPC date</td></tr>
      <tr><td style="color:#">From:&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
        <input type="date" class="form-control" id="d1" name="d1" required> 
      </td><td style="color:#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>
        <input type="date" class="form-control" id="d2" name="d2" required>
      </td></tr>

      <tr><td><br>  </td></tr>
      <tr><td style="color:#0000ff">Feedback:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="font-size:13px;">
      
      {% for radio in form.feed_sts %}
        <div class="myradio">
        {{ radio }}
        </div>
      {% endfor %}
      </td></tr>


      <!-- po_reason is used for capturing portout msisdn reqd purpose -->
      <tr><td><br>  </td></tr>
      <tr><td style="color:#0000ff">Portout status:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td style="font-size:13px;">
      {% for radio in form.port_sts %}
        <div class="myradio">
        {{ radio }}
        </div>
      {% endfor %}
      </td></tr>
      
    </table> 
    <br>
      <button type="reset" class="btn btn-warning" id="id_clear_filters" onclick="return resetForm(this.form);">
        Reset form
      </button>
              
  </b>    
  </form>

  <form action="{% url 'search_results4' %}" method="get">
    <table style="width:50%">
      <tr>
        <td style="color:#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;
          
        
        </td></tr>
        <tr>
        <td>
          
          <button type="submit" class="export" form="ssaForm"
          formaction="{% url 'search_results4' %}"><i class="fa fa-search" aria-hidden="true"></i>&nbsp;Search</button>
        </td>
        <td><button type="submit" class="export" form="ssaForm" formaction="{% url 'csv_ssa_wise' %}" >
          <i class="fas fa-download"></i>&nbsp; DOWNLOAD</button>
        </td>        
      </tr>
    </table>    
    
  </form>

  <script>
      $("#id_circle").change(function () {
        var url = $("#ssaForm").attr("data-ssas-url");  
        var circleId = $(this).val();  
  
        $.ajax({                      
          url: url,                    
          data: {
            'circle_id': circleId       
          },
          success: function (data) {  
            $("#id_ssa").html(data);  
          }
        });
  
      });
    </script>
  
{% endblock %}